### ISSUE TITLE
Update chainspec

### ISSUE THREAD

**Issue by avive** [karma-coin/karmachain#126]
Create TN3 chainspec which is very close to genesis chainspec in terms of values according to the economic model.

**Comment by HolyGrease** [comment]
We need to determine values of next parameters:
1. Max number of validators
2. Minimal amount to bond to validate
3. Minimal amount to bond to nominate
4. Minimal amount to join the nomination pool
5. Minimal amount to create the nomination pool
6. Initial balance of genesis validator (should be greater or equal to `minimal amount to bond to validate`)
7. Some genesis balances, like above or funds for off chain account in order to sign karma rewards

**Comment by HolyGrease** [comment]
- [ ] Set era = 24 hours
- [ ] Set epoch = 4 hours
- [ ] Set active validator slots = 10

**Comment by avive** [comment]
We need to finalize lots of params / consts: 

Nomination and staking
- Min nominator stake amount
- Max number of nominators.
- Max active set of validators - should be 10.
- Min stake per validator - todo: add amount here.
- what else?

Nomination pools
- max number of pools
- max number of members per pool
- minimum pool stake amount - should be 1 KC.
- max numbers of total pool members - I see it is limited in polka.


@HolyGrease I'd like to have a google sheet with all network params / constants for TN3 so there's one place to look up all the numbers. I will create one and share with you.

**Comment by avive** [comment]
Add all consts / params to the shared sheet.
