### ISSUE TITLE
Update tx fees

### ISSUE THREAD

**Issue by avive** [karma-coin/karmachain#82]
Critical to get fees to very low KCENT numbers - some TN1 fees are in the hundreds millions range!

**Comment by avive** [comment]
Can't we just hard-code 1KCent tx fee for every tx instead of current 100 KCents.

**Comment by HolyGrease** [comment]
Yes we can, but it is a good practice to have benchmarks done. Benchmarks determine transactions weights and this influence how transactions will be included in the block. This can save blockchain from throttle because too many transactions was put in the one single block.

I think we can put this on hold for now and decide later when we have time to implements this

**Comment by avive** [comment]
Can you please make all tx fees 1 KCENT instead of 100 for TN3?
