### ISSUE TITLE
Implement Verifier node role

### ISSUE THREAD

**Issue by avive** [karma-coin/karmachain#84]
We need to implement the verifier role for nodes. The high-level design:
1. Node can be configured to run as verifier.
2. Verifier has a keypair for signing messages. It should be provided at node startup via config file.
3. Chainspec includes the supported verifier identity (public key) and dialup info (api public endpoint).
4. We will setup and maintain a public node configured as the chainspec verifier as part of every kc2.0 net. e.g. testnet, mainnet.
5. Verify API should be part of the node api but should only be available if node is configured as verifier on startup.
6. Clients will use the chainspec info to call the public api of the supported verifier for the network they are on.
7. Verifier should use the light microservice that is a proxy to firebase users db. https://github.com/karma-coin/karmacoin-verifier. This microservice can be used by multiple networks. The dialup info of the webservice should be part of the verifier config on startup.
8. Signup and user update tx processing must verify signature on data provided by the verifier (evidence) using the public key from chainspec.

References:

- Verifier VerifyNumber api implementation: https://github.com/karma-coin/karmacoin-server/blob/main/crates/server/src/services/verifier/verify_number.rs

- Look at KC 1.0 signup tx processing for where the verifier signature is checked on the data it provides in the tx.

**Comment by HolyGrease** [comment]
The idea with multi signature and off chain worker sound great but has a lot of disadvantages:
1. Using multi signature takes at least two blocks to actually sign up (1 block for user signature and next block will receive second signature if off chain worker fast enough).
2. Substrate off chain worker is very restricted, one of the restriction is that it have to use `no_std` feature, that means that we cannot use the bigger part of external packages. For example we cannot use `gRPC` and have only `HTTP` option, so in order to implement this we need to adjust `Karmacoin verifier`, sound not good for me.
And there are another problems...
